import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  threads: defineTable({
    title: v.string(),
    userId: v.string(),
    updatedAt: v.number(),
    pinned: v.optional(v.boolean()),
    branchedFrom: v.optional(v.id("threads")),

    status: v.optional(
      v.union(v.literal("pending"), v.literal("complete"), v.literal("streaming")),
    ),
  })
    .index("by_userId", ["userId"])
    .index("by_userId_updatedAt", ["userId", "updatedAt"])
    .index("by_userId_pinned_updatedAt", ["userId", "pinned", "updatedAt"])
    .searchIndex("search_title", { searchField: "title", filterFields: ["userId", "pinned"] }),

  attachments: defineTable({
    id: v.string(),
    name: v.string(),
    size: v.number(),
    type: v.union(v.literal("image"), v.literal("pdf")),
    // Indicates whether the attachment was generated by the assistant or uploaded by the user.
    // Temporarily optional for migration/backfill; code defaults to "user" when absent.
    source: v.optional(v.union(v.literal("assistant"), v.literal("user"))),
    userId: v.string(),
    threadId: v.id("threads"),
  }).index("by_userId", ["userId"]),

  messages: defineTable({
    threadId: v.id("threads"),
    userId: v.string(),

    messageId: v.string(),
    content: v.string(),
    reasoning: v.optional(v.string()),
    error: v.optional(v.string()),

    model: v.string(),
    status: v.union(
      v.literal("pending"),
      v.literal("complete"),
      v.literal("streaming"),
      v.literal("error"),
    ),

    role: v.union(v.literal("assistant"), v.literal("user")),
    resumableStreamId: v.optional(v.union(v.string(), v.null())),

    modelParams: v.optional(
      v.object({
        webSearchEnabled: v.optional(v.boolean()),
        effort: v.optional(v.union(v.literal("low"), v.literal("medium"), v.literal("high"))),
      }),
    ),

    createdAt: v.number(),
    updatedAt: v.number(),

    sources: v.optional(
      v.array(v.object({ id: v.string(), title: v.optional(v.string()), url: v.string() })),
    ),

    attachments: v.optional(v.array(v.id("attachments"))),
    metadata: v.optional(
      v.object({
        model: v.optional(v.string()),
        duration: v.number(),
        finishReason: v.string(),
        totalTokens: v.number(),
        thinkingTokens: v.number(),
        // New optional metric: time to first token in milliseconds
        timeToFirstTokenMs: v.optional(v.number()),

        // Reference to AI profile applied when generating this message
        aiProfileId: v.optional(v.id("ai_profiles")),

        durations: v.optional(
          v.object({ request: v.number(), reasoning: v.number(), text: v.number() }),
        ),
      }),
    ),
  })
    .index("by_userId_threadId", ["userId", "threadId"])
    .index("by_threadId", ["threadId"])
    .index("by_messageId", ["messageId"]),

  ai_profiles: defineTable({
    userId: v.string(),
    name: v.string(),
    systemPrompt: v.string(),
    imageKey: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_userId", ["userId"])
    .index("by_userId_updatedAt", ["userId", "updatedAt"])
    .index("by_userId_createdAt", ["userId", "createdAt"])
    .searchIndex("search_name", { searchField: "name", filterFields: ["userId"] }),

  users: defineTable({
    userId: v.string(),

    username: v.union(v.string(), v.null()),
    emailAddress: v.union(v.string(), v.null()),
    imageUrl: v.union(v.string(), v.null()),

    isBanned: v.optional(v.boolean()),

    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),

    customization: v.optional(
      v.object({
        name: v.optional(v.string()),
        occupation: v.optional(v.string()),
        traits: v.optional(v.array(v.string())),
        systemInstruction: v.optional(v.string()),
        backgroundId: v.optional(v.union(v.string(), v.null())),
        disableBlur: v.optional(v.boolean()),
        hiddenModels: v.optional(v.array(v.string())),
      }),
    ),
  }).index("by_userId", ["userId"]),

  usages: defineTable({
    userId: v.string(),
    used: v.number(),
    base: v.number(),
    resetAt: v.number(),
  }).index("by_userId", ["userId"]),

  user_stats: defineTable({
    userId: v.string(),

    stats: v.object({
      threads: v.number(),
      words: v.number(),
      messages: v.object({ assistant: v.number(), user: v.number() }),
      // Split word counts by role for UI cards; kept optional for backward compatibility
      wordsByRole: v.optional(v.object({ assistant: v.number(), user: v.number() })),
    }),

    modelCounts: v.record(v.string(), v.number()),
    threadCounts: v.record(v.id("threads"), v.number()),
    activityCounts: v.record(v.string(), v.number()),
    aiProfileCounts: v.record(v.string(), v.number()),

    lastUpdatedAt: v.number(),
  }).index("by_userId", ["userId"]),
});
