[install]
linker = "hoisted"

# Only install package versions published at least 24 hours ago
minimumReleaseAge = 86400

# These packages will bypass the 1-day minimum age requirement
minimumReleaseAgeExcludes = ["@types/bun", "bun-types"]
