/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SettingsRouteImport } from './app/settings'
import { Route as ChatRouteImport } from './app/_chat'
import { Route as ChatIndexRouteImport } from './app/_chat.index'
import { Route as ShareShareIdRouteImport } from './app/share.$shareId'
import { Route as SettingsThreadsRouteImport } from './app/settings/threads'
import { Route as SettingsAccountRouteImport } from './app/settings/account'
import { Route as AuthLogoutRouteImport } from './app/auth.logout'
import { Route as AuthLoginRouteImport } from './app/auth.login'
import { Route as SettingsStatisticsRouteRouteImport } from './app/settings/statistics/route'
import { Route as SettingsProfilesRouteRouteImport } from './app/settings/profiles.route'
import { Route as SettingsModelsRouteRouteImport } from './app/settings/models/route'
import { Route as SettingsCustomizationRouteRouteImport } from './app/settings/customization/route'
import { Route as SettingsAttachmentsRouteRouteImport } from './app/settings/attachments/route'
import { Route as ChatThreadsRouteRouteImport } from './app/_chat.threads.route'
import { Route as ApiAuthCallbackRouteImport } from './app/api/auth/callback'
import { Route as ChatThreadsThreadIdRouteImport } from './app/_chat.threads.$threadId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThreadsRoute = SettingsThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStatisticsRouteRoute = SettingsStatisticsRouteRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfilesRouteRoute = SettingsProfilesRouteRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelsRouteRoute = SettingsModelsRouteRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCustomizationRouteRoute =
  SettingsCustomizationRouteRouteImport.update({
    id: '/customization',
    path: '/customization',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsAttachmentsRouteRoute =
  SettingsAttachmentsRouteRouteImport.update({
    id: '/attachments',
    path: '/attachments',
    getParentRoute: () => SettingsRoute,
  } as any)
const ChatThreadsRouteRoute = ChatThreadsRouteRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => ChatRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadsThreadIdRoute = ChatThreadsThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatThreadsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/threads': typeof ChatThreadsRouteRouteWithChildren
  '/settings/attachments': typeof SettingsAttachmentsRouteRoute
  '/settings/customization': typeof SettingsCustomizationRouteRoute
  '/settings/models': typeof SettingsModelsRouteRoute
  '/settings/profiles': typeof SettingsProfilesRouteRoute
  '/settings/statistics': typeof SettingsStatisticsRouteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/threads': typeof SettingsThreadsRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/threads/$threadId': typeof ChatThreadsThreadIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteWithChildren
  '/threads': typeof ChatThreadsRouteRouteWithChildren
  '/settings/attachments': typeof SettingsAttachmentsRouteRoute
  '/settings/customization': typeof SettingsCustomizationRouteRoute
  '/settings/models': typeof SettingsModelsRouteRoute
  '/settings/profiles': typeof SettingsProfilesRouteRoute
  '/settings/statistics': typeof SettingsStatisticsRouteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/threads': typeof SettingsThreadsRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/': typeof ChatIndexRoute
  '/threads/$threadId': typeof ChatThreadsThreadIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/threads': typeof ChatThreadsRouteRouteWithChildren
  '/settings/attachments': typeof SettingsAttachmentsRouteRoute
  '/settings/customization': typeof SettingsCustomizationRouteRoute
  '/settings/models': typeof SettingsModelsRouteRoute
  '/settings/profiles': typeof SettingsProfilesRouteRoute
  '/settings/statistics': typeof SettingsStatisticsRouteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/threads': typeof SettingsThreadsRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/threads/$threadId': typeof ChatThreadsThreadIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/threads'
    | '/settings/attachments'
    | '/settings/customization'
    | '/settings/models'
    | '/settings/profiles'
    | '/settings/statistics'
    | '/auth/login'
    | '/auth/logout'
    | '/settings/account'
    | '/settings/threads'
    | '/share/$shareId'
    | '/threads/$threadId'
    | '/api/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/threads'
    | '/settings/attachments'
    | '/settings/customization'
    | '/settings/models'
    | '/settings/profiles'
    | '/settings/statistics'
    | '/auth/login'
    | '/auth/logout'
    | '/settings/account'
    | '/settings/threads'
    | '/share/$shareId'
    | '/'
    | '/threads/$threadId'
    | '/api/auth/callback'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/_chat/threads'
    | '/settings/attachments'
    | '/settings/customization'
    | '/settings/models'
    | '/settings/profiles'
    | '/settings/statistics'
    | '/auth/login'
    | '/auth/logout'
    | '/settings/account'
    | '/settings/threads'
    | '/share/$shareId'
    | '/_chat/'
    | '/_chat/threads/$threadId'
    | '/api/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/threads': {
      id: '/settings/threads'
      path: '/threads'
      fullPath: '/settings/threads'
      preLoaderRoute: typeof SettingsThreadsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/statistics': {
      id: '/settings/statistics'
      path: '/statistics'
      fullPath: '/settings/statistics'
      preLoaderRoute: typeof SettingsStatisticsRouteRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profiles': {
      id: '/settings/profiles'
      path: '/profiles'
      fullPath: '/settings/profiles'
      preLoaderRoute: typeof SettingsProfilesRouteRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/customization': {
      id: '/settings/customization'
      path: '/customization'
      fullPath: '/settings/customization'
      preLoaderRoute: typeof SettingsCustomizationRouteRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/attachments': {
      id: '/settings/attachments'
      path: '/attachments'
      fullPath: '/settings/attachments'
      preLoaderRoute: typeof SettingsAttachmentsRouteRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/threads': {
      id: '/_chat/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ChatThreadsRouteRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/threads/$threadId': {
      id: '/_chat/threads/$threadId'
      path: '/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ChatThreadsThreadIdRouteImport
      parentRoute: typeof ChatThreadsRouteRoute
    }
  }
}

interface ChatThreadsRouteRouteChildren {
  ChatThreadsThreadIdRoute: typeof ChatThreadsThreadIdRoute
}

const ChatThreadsRouteRouteChildren: ChatThreadsRouteRouteChildren = {
  ChatThreadsThreadIdRoute: ChatThreadsThreadIdRoute,
}

const ChatThreadsRouteRouteWithChildren =
  ChatThreadsRouteRoute._addFileChildren(ChatThreadsRouteRouteChildren)

interface ChatRouteChildren {
  ChatThreadsRouteRoute: typeof ChatThreadsRouteRouteWithChildren
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadsRouteRoute: ChatThreadsRouteRouteWithChildren,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAttachmentsRouteRoute: typeof SettingsAttachmentsRouteRoute
  SettingsCustomizationRouteRoute: typeof SettingsCustomizationRouteRoute
  SettingsModelsRouteRoute: typeof SettingsModelsRouteRoute
  SettingsProfilesRouteRoute: typeof SettingsProfilesRouteRoute
  SettingsStatisticsRouteRoute: typeof SettingsStatisticsRouteRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsThreadsRoute: typeof SettingsThreadsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAttachmentsRouteRoute: SettingsAttachmentsRouteRoute,
  SettingsCustomizationRouteRoute: SettingsCustomizationRouteRoute,
  SettingsModelsRouteRoute: SettingsModelsRouteRoute,
  SettingsProfilesRouteRoute: SettingsProfilesRouteRoute,
  SettingsStatisticsRouteRoute: SettingsStatisticsRouteRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsThreadsRoute: SettingsThreadsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  ShareShareIdRoute: ShareShareIdRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
