import { getModelData } from "@/lib/chat/models";
import type { ChatMessage } from "@/lib/types";
import { format } from "@/lib/utils";

export function MessageMetadata({
  metadata,
  model,
  hiddenReasoning,
}: {
  metadata: ChatMessage["metadata"];
  model: string;
  hiddenReasoning?: boolean;
}) {
  if (!metadata) return null;

  return (
    <div className="text-muted-foreground/90 flex flex-wrap items-center gap-1.5 text-sm select-none">
      <span>{format.time(metadata.duration / 1000)}</span>
      <span>-</span>
      <span>Generated By {getModelData(model)?.displayName}</span>
      <span>-</span>
      <span>{format.number(metadata.totalTokens)} Tokens</span>
      {metadata.thinkingTokens > 0 && (
        <>
          <span>-</span>
          <span>
            {format.number(metadata.thinkingTokens)} {hiddenReasoning ? "Hidden" : ""} Thinking Tokens
          </span>
        </>
      )}
    </div>
  );
}
